name: build_container

on:
    push:
        branches: [main]
    pull_request: 
        branches: [main]
        types: [closed]
    workflow_dispatch:  

jobs:
    build_and_deploy_back:
        name: build_and_deploy_frontend
        runs-on: ubuntu_latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: Set script permissions
              run: chmod +x ./build-all.sh        
            - name: build and push Docker image
              uses: docker/build-push-action@v1
              with:
                username: ${{secrets.DOCKER_USERNAME}}
                password: ${{secrets.DOCKER_PASSWORD}}
                repository:
                dockerfile: Dockerfile
                tags: latest
                
      

