name: Trigger Local Container Build

on:
    push:
        branches: [main]
    pull_request: 
        branches: [main]
        types: [closed]
    workflow_dispatch:  


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Trigger local build
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key
          chmod 600 private_key
          scp -i private_key -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -r . leul@leul-HP-Pavilion-Laptop-15-cs3xxx:/Documents 

          ssh -i private_key leul@leul-HP-Pavilion-Laptop-15-cs3xxx "bash /Documents/build_and_run_docker.sh"
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}


